/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAppRouteImport } from './routes/admin.$app'
import { Route as ApiPublicRolesSyncRouteImport } from './routes/api/public/roles/sync'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/admin/$app',
  path: '/admin/$app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRolesSyncRoute = ApiPublicRolesSyncRouteImport.update({
  id: '/api/public/roles/sync',
  path: '/api/public/roles/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$app': typeof AdminAppRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/public/roles/sync': typeof ApiPublicRolesSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$app': typeof AdminAppRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/public/roles/sync': typeof ApiPublicRolesSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$app': typeof AdminAppRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/public/roles/sync': typeof ApiPublicRolesSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/$app'
    | '/admin/audit'
    | '/admin/security'
    | '/api/public/roles/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/$app'
    | '/admin/audit'
    | '/admin/security'
    | '/api/public/roles/sync'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/$app'
    | '/admin/audit'
    | '/admin/security'
    | '/api/public/roles/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAppRoute: typeof AdminAppRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  ApiPublicRolesSyncRoute: typeof ApiPublicRolesSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$app': {
      id: '/admin/$app'
      path: '/admin/$app'
      fullPath: '/admin/$app'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roles/sync': {
      id: '/api/public/roles/sync'
      path: '/api/public/roles/sync'
      fullPath: '/api/public/roles/sync'
      preLoaderRoute: typeof ApiPublicRolesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAppRoute: AdminAppRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  ApiPublicRolesSyncRoute: ApiPublicRolesSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
